export const ANIMATION_DEFAULTS = {
  ENTRANCE_FADE_DURATION: 800,
  ENTRANCE_SCALE_DURATION: 500,
  ENTRANCE_TRANSLATE_DURATION: 500,
  BUTTON_APPEAR_DURATION: 600,
  PULSE_DURATION: 1000,
  SPIN_DURATION: 1000,
  PARTICLE_BASE_DURATION: 4000,
  PARTICLE_RANDOM_DURATION: 3000,
};